version: "3.9"

services:
    app:
        build:
            context: .
        image: ghcr.io/testausserveri/koirameili
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 25:25
            - 8080:4000
        security_opt:
            - seccomp:seccomp-chrome.json
    db:
        image: mariadb:10.8
        restart: always
        volumes:
        - ./db_data/:/var/lib/mysql
        environment:
        - MARIADB_ROOT_HOST=%
        - MARIADB_RANDOM_ROOT_PASSWORD=yes