name: Deploy

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest

    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/app/
            docker-compose down
            docker-compose pull
            authbind --deep docker-compose up -d
