name: Publish Docker image

on:
  release:
    types: [published]
permissions:
  contents: read
  packages: write

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          attests: type=sbom
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/testausserveri/koirameili:latest,ghcr.io/testausserveri/koirameili:${{ github.event.release.tag_name }}
          
